// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mcp.server.enabled": boolean;
      "mcp.server.port": number;
      "scihub.enabled": boolean;
      "scihub.sources": string;
      "scihub.proxy.enabled": boolean;
      "scihub.proxy.host": string;
      "scihub.proxy.port": number;
      "wos.enabled": boolean;
      "wos.apiKey": string;
      "wos.plan": string;
      "wos.database": string;
      "wos.maxRecords": number;
      "wos.timeoutSeconds": number;
      "wos.usageDateUtc": string;
      "wos.requestsToday": number;
    };
  }
}
